Cybersecurity Section Addition
setupmd/docs pull request #155
Opened 2024-10-15 01:53 UTC by InfraCharm

## Description

This adds a basic cybersecurity section that will be built upon over time depending on world events or user feedback.

## Resolved issues

Answers questions about Server Security and best practices.

2024-10-15 04:12 UTC, thewilloftheshadow requested changes

2024-10-15 04:12 UTC, thewilloftheshadow commented on src/content/docs/security/firewalls.mdx
> +A basic firewall setup on linux for a Minecraft server running Pterodactyl would look like this:
Would be good to note here that docker by default bypasses ufw

2024-10-15 04:39 UTC, InfraCharm commented on src/content/docs/security/firewalls.mdx
> +A basic firewall setup on linux for a Minecraft server running Pterodactyl would look like this:
added!

2024-10-15 11:37 UTC, funniray commented on src/content/docs/security/basicsecurity.mdx
> +    <li>CVE-2023-29347 - Steam Client Vulnerability</li>
[CVE-2022-21658](https://nvd.nist.gov/vuln/detail/CVE-2022-21658) isn't a Minecraft RCE and [CVE-2023-29347](https://nvd.nist.gov/vuln/detail/CVE-2023-29347) isn't a steam client vulnerability

2024-10-15 16:38 UTC, InfraCharm commented on src/content/docs/security/basicsecurity.mdx
> +    <li>CVE-2023-29347 - Steam Client Vulnerability</li>
Correct. I've removed them. Thank you. 

Not sure where I got that info from, I think NVD.

2024-10-23 02:53 UTC, DominicTWHV commented on src/content/docs/security/firewalls.mdx
> +You can find many tutorials online about the use of UFW. If you wanted a more advanced approach with more control, you can look into using IPTables.
iirc UFW sometimes does not automatically start after reboot, make sure the service is enabled on startup

2024-10-23 02:54 UTC, DominicTWHV commented on src/content/docs/security/firewalls.mdx
> +You can find many tutorials online about the use of UFW. If you wanted a more advanced approach with more control, you can look into using IPTables.
```
sudo systemctl status ufw
sudo systemctl enable ufw
```

2025-10-14 22:14 UTC, closed without merging